name: testflinger-cli
version: 0.1
summary: testflinger-cli
description: |
  The testflinger-cli tool is used for interacting with the testflinger
  server for submitting test jobs, checking status, getting results, and
  streaming output.
confinement: strict

apps:
  testflinger-cli:
    command: bin/testflinger-cli.wrapper
    plugs:
      - home
      - network

parts:
  launcher:
    plugin: dump
    source: .
    organize:
      testflinger-cli.wrapper: bin/testflinger-cli.wrapper
  testflinger-cli:
    plugin: python
    source: .
