device_ip: 10.102.182.216
reboot_script: 
  #  - "sshpass -p 'ubuntu' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@10.102.182.216 -- sudo reboot"
  - "sshpass -p 'ubuntu' ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@10.102.182.216 'echo ubuntu | sudo -S reboot'"
control_host: 10.102.239.214
