name: Run unit tests

on:
  push:
    branches: [ main ]
    paths:
      - testflinger-cli/**
  pull_request:
    branches: [ main ]
    paths:
      - testflinger-cli/**

jobs:
  build:
    defaults:
      run:
        working-directory: testflinger-cli
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: Install tox
      run: pip install tox
    - name: Run tests
      run: |
        tox
