name: "[device-connectors] Run unit tests"
permissions:
  contents: read
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - .github/workflows/device-tox.yml
      - device-connectors/**
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/device-tox.yml
      - device-connectors/**

jobs:
  build:
    defaults:
      run:
        working-directory: device-connectors
    runs-on: [self-hosted, linux, jammy, X64]
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          persist-credentials: false
      - name: Install uv and set up Python
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182 # v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: uvx --with tox-uv tox
